#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Definitive Catalog
Pre-loaded items seed data for the items_catalog table
Generated from medicamentos_dosagens_simples.json
"""

DEFINITIVE_CATALOG: list[tuple[str, str]] = [
    ("abatacepte 125 mg injetável", "un"),
    ("abatacepte 250 mg injetável", "un"),
    ("acetazolamida 250 mg", "un"),
    ("acitretina 10 mg", "un"),
    ("acitretina 25 mg", "un"),
    ("adalimumabe 40 mg injetável", "un"),
    ("alentuzumabe 10 mg/mL", "un"),
    ("alfadornase 2,5 mg", "un"),
    ("alfaelosulfase 1 mg/mL injetável", "un"),
    ("alfaepoetina 1.000 UI injetável", "un"),
    ("alfaepoetina 10.000 UI injetável", "un"),
    ("alfaepoetina 2.000 UI injetável", "un"),
    ("alfaepoetina 3.000 UI injetável", "un"),
    ("alfaepoetina 4.000 UI injetável", "un"),
    ("alfagalsidase 1 mg/mL", "un"),
    ("alfaglicosidase 50 mg", "un"),
    ("alfainterferona 2b 10.000.000 UI injetável", "un"),
    ("alfainterferona 2b 3.000.000 UI injetável", "un"),
    ("alfainterferona 2b 5.000.000 UI injetável", "un"),
    ("alfataliglicerase 200 UI injetável", "un"),
    ("alfavelaglicerase 400 U injetável", "un"),
    ("alfavestronidase 10 mg injetável", "un"),
    ("amantadina 100 mg", "un"),
    ("ambrisentana 10 mg", "un"),
    ("ambrisentana 5 mg", "un"),
    ("atorvastatina 10 mg", "un"),
    ("atorvastatina 20 mg", "un"),
    ("atorvastatina 40 mg", "un"),
    ("atorvastatina 80 mg", "un"),
    ("azatioprina 50 mg", "un"),
    ("baricitinibe 2 mg", "un"),
    ("baricitinibe 4 mg", "un"),
    ("beclometasona + formoterol + glicopirrônio 100 µg + 6 µg + 12,5 µg", "un"),
    ("betainterferona 12.000.000 UI injetável", "un"),
    ("betainterferona 44 mcg injetável", "un"),
    ("bezafibrato 200 mg", "un"),
    ("bezafibrato 400 mg", "un"),
    ("bimatoprosta 0,3 mg/mL solução oftálmica", "un"),
    ("biotina 2,5 mg", "un"),
    ("bosentana 125 mg", "un"),
    ("bosentana 62,5 mg", "un"),
    ("brimonidina 2,0 mg/mL solução oftálmica", "un"),
    ("brinzolamida 10 mg/mL suspensão oftálmica", "un"),
    ("budesonida 400 mcg", "un"),
    ("burosumabe 10 mg/mL injetável", "un"),
    ("burosumabe 20 mg/mL injetável", "un"),
    ("burosumabe 30 mg/mL injetável", "un"),
    ("cabergolina 0,5 mg", "un"),
    ("calcipotriol 50 mcg pomada", "un"),
    ("calcitonina 200 UI spray nasal", "un"),
    ("calcitriol 0,25 mcg cápsula", "un"),
    ("certolizumabe pegol 200 mg injetável", "un"),
    ("ciclofosfamida 50 mg", "un"),
    ("ciclosporina 10 mg", "un"),
    ("ciclosporina 100 mg", "un"),
    ("ciclosporina 100 mg/mL solução oral", "un"),
    ("ciclosporina 25 mg", "un"),
    ("ciclosporina 50 mg", "un"),
    ("cinacalcete 30 mg", "un"),
    ("cinacalcete 60 mg", "un"),
    ("ciprofibrato 100 mg", "un"),
    ("ciproterona 50 mg", "un"),
    ("cladribina 10 mg", "un"),
    ("clobazam 10 mg", "un"),
    ("clobazam 20 mg", "un"),
    ("clobetasol 0,5 mg/g creme", "un"),
    ("clobetasol 0,5 mg/g solução capilar", "un"),
    ("clopidogrel 75 mg", "un"),
    ("cloroquina 150 mg", "un"),
    ("clozapina 100 mg", "un"),
    ("clozapina 25 mg", "un"),
    ("codeína 3 mg/mL solução oral", "un"),
    ("codeína 30 mg/mL injetável", "un"),
    ("danazol 100 mg", "un"),
    ("danazol 200 mg", "un"),
    ("dapagliflozina 10 mg", "un"),
    ("deferasirox 125 mg", "un"),
    ("deferasirox 250 mg", "un"),
    ("deferasirox 500 mg", "un"),
    ("deferiprona 1000 mg", "un"),
    ("deferiprona 500 mg", "un"),
    ("desferroxamina 500 mg injetável", "un"),
    ("desmopressina 0,1 mg solução nasal", "un"),
    ("desmopressina 0,1 mg/mL solução nasal", "un"),
    ("desmopressina 0,2 mg solução nasal", "un"),
    ("donepezila 10 mg", "un"),
    ("donepezila 5 mg", "un"),
    ("eculizumabe 10 mg/mL injetável", "un"),
    ("eltrombopague olamina 25 mg", "un"),
    ("eltrombopague olamina 50 mg", "un"),
    ("enoxaparina sódica 40 mg", "un"),
    ("enoxaparina sódica 60 mg", "un"),
    ("entacapona 200 mg", "un"),
    ("etanercepte 25 mg injetável", "un"),
    ("etossuximida 50 mg/mL xarope", "un"),
    ("everolimo 0,5 mg", "un"),
    ("everolimo 0,75 mg", "un"),
    ("everolimo 1 mg", "un"),
    ("fenofibrato 200 mg", "un"),
    ("fenofibrato 250 mg", "un"),
    ("fenoterol 100 mcg aerossol", "un"),
    ("filgrastim 300 mcg injetável", "un"),
    ("fingolimode 0,5 mg", "un"),
    ("fludrocortisona 0,1 mg", "un"),
    ("formoterol 12 mcg", "un"),
    ("formoterol + budesonida 12 mcg + 400 mcg", "un"),
    ("fumarato de dimetila 120 mg", "un"),
    ("fumarato de dimetila 240 mg", "un"),
    ("furoato de fluticasona + brometo de umeclidínio + trifenato de vilanterol 100 mcg + 62,5 mcg + 25 mcg", "un"),
    ("gabapentina 300 mg", "un"),
    ("gabapentina 400 mg", "un"),
    ("galantamina 16 mg", "un"),
    ("galantamina 24 mg", "un"),
    ("galantamina 8 mg", "un"),
    ("galsulfase 1 mg/mL injetável", "un"),
    ("genfibrozila 600 mg", "un"),
    ("genfibrozila 900 mg", "un"),
    ("glatiramer 40 mg injetável", "un"),
    ("golimumabe 50 mg injetável", "un"),
    ("gosserrelina 10,8 mg injetável", "un"),
    ("gosserrelina 3,6 mg injetável", "un"),
    ("hidroxicloroquina 400 mg", "un"),
    ("hidroxiuréia 100 mg", "un"),
    ("hidroxiuréia 500 mg", "un"),
    ("idursulfase alfa 2 mg/mL injetável", "un"),
    ("iloprosta 10 mcg/mL solução para nebulização", "un"),
    ("imiglucerase 400 UI injetável", "un"),
    ("imunoglobulina humana 0,5 g injetável", "un"),
    ("imunoglobulina humana 1 g injetável", "un"),
    ("imunoglobulina humana 2,5 g injetável", "un"),
    ("imunoglobulina humana 5,0 g injetável", "un"),
    ("infliximabe 10 mg/mL injetável", "un"),
    ("infliximabe 100 mg injetável", "un"),
    ("insulina análoga de ação prolongada 100 UI/mL", "un"),
    ("insulina análoga de ação rápida 100 UI/mL", "un"),
    ("isotretinoína 10 mg", "un"),
    ("isotretinoína 20 mg", "un"),
    ("ivacaftor 150 mg", "un"),
    ("ivacaftor / elexacaftor / tezacaftor + ivacaftor 25 mg", "un"),
    ("ivacaftor / elexacaftor / tezacaftor + ivacaftor 37,5 mg", "un"),
    ("ivacaftor / elexacaftor / tezacaftor + ivacaftor 50 mg", "un"),
    ("lamotrigina 100 mg", "un"),
    ("lamotrigina 25 mg", "un"),
    ("lamotrigina 50 mg", "un"),
    ("lanreotida 120 mg injetável", "un"),
    ("lanreotida 60 mg injetável", "un"),
    ("lanreotida 90 mg injetável", "un"),
    ("laronidase 0,58 mg/mL injetável", "un"),
    ("latanoprosta 0,05 mg/mL solução oftálmica", "un"),
    ("leflunomida 20 mg", "un"),
    ("leuprorrelina 3,75 mg injetável", "un"),
    ("leuprorrelina 45 mg injetável", "un"),
    ("levetiracetam 100 mg/mL solução oral", "un"),
    ("levetiracetam 1000 mg", "un"),
    ("levetiracetam 250 mg", "un"),
    ("levetiracetam 500 mg", "un"),
    ("levetiracetam 750 mg", "un"),
    ("memantina 10 mg", "un"),
    ("mepolizumabe 100 mg/mL injetável", "un"),
    ("mesalazina 400 mg", "un"),
    ("mesalazina 500 mg", "un"),
    ("mesalazina 800 mg", "un"),
    ("metadona 10 mg", "un"),
    ("metadona 10 mg/mL injetável", "un"),
    ("metadona 5 mg", "un"),
    ("metilprednisolona 500 mg injetável", "un"),
    ("metotrexato 2,5 mg", "un"),
    ("metotrexato 25 mg/mL injetável", "un"),
    ("micofenolato de mofetila 500 mg", "un"),
    ("micofenolato de sódio 180 mg", "un"),
    ("micofenolato de sódio 360 mg", "un"),
    ("miglustate 100 mg", "un"),
    ("morfina 10 mg/mL injetável", "un"),
    ("morfina 10 mg/mL solução oral", "un"),
    ("naproxeno 250 mg", "un"),
    ("naproxeno 500 mg", "un"),
    ("natalizumabe 300 mg", "un"),
    ("nusinersena 2,4 mg/mL injetável", "un"),
    ("octreotida 0,1 mg/mL injetável", "un"),
    ("octreotida 10 mg injetável", "un"),
    ("octreotida 20 mg injetável", "un"),
    ("octreotida 30 mg injetável", "un"),
    ("olanzapina 10 mg", "un"),
    ("olanzapina 5 mg", "un"),
    ("omalizumabe 150 mg", "un"),
    ("pamidronato 60 mg injetável", "un"),
    ("pancreatina 10.000 UI cápsula", "un"),
    ("pancreatina 25.000 UI cápsula", "un"),
    ("paricalcitol 5,0 mcg/mL", "un"),
    ("penicilamina 250 mg", "un"),
    ("pilocarpina 20 mg/mL solução oftálmica", "un"),
    ("piridostigmina 60 mg", "un"),
    ("pramipexol 0,125 mg", "un"),
    ("pramipexol 0,25 mg", "un"),
    ("pramipexol 1 mg", "un"),
    ("pravastatina 10 mg", "un"),
    ("pravastatina 20 mg", "un"),
    ("pravastatina 40 mg", "un"),
    ("primidona 100 mg", "un"),
    ("primidona 250 mg", "un"),
    ("quetiapina 100 mg", "un"),
    ("quetiapina 200 mg", "un"),
    ("quetiapina 25 mg", "un"),
    ("quetiapina 300 mg", "un"),
    ("raloxifeno 60 mg", "un"),
    ("rasagilina 1 mg", "un"),
    ("riluzol 50 mg", "un"),
    ("risanquizumabe 150 mg/mL", "un"),
    ("risdiplam 0,75 mg/mL solução oral", "un"),
    ("risedronato 35 mg", "un"),
    ("risperidona 1 mg", "un"),
    ("risperidona 1 mg/mL solução oral", "un"),
    ("risperidona 2 mg", "un"),
    ("risperidona 3 mg", "un"),
    ("rituximabe 500 mg injetável", "un"),
    ("rivastigmina 1,5 mg", "un"),
    ("rivastigmina 3 mg", "un"),
    ("rivastigmina 4,5 mg", "un"),
    ("rivastigmina 6 mg", "un"),
    ("sacarato de hidróxido férrico 100 mg injetável", "un"),
    ("sacubitril valsartana 100 mg", "un"),
    ("sacubitril valsartana 200 mg", "un"),
    ("sacubitril valsartana 50 mg", "un"),
    ("sapropterina 100 mg", "un"),
    ("secuquinumabe 150 mg/mL injetável", "un"),
    ("selexipague 1000 mcg", "un"),
    ("selexipague 1200 mcg", "un"),
    ("selexipague 1400 mcg", "un"),
    ("selexipague 200 mcg", "un"),
    ("selexipague 400 mcg", "un"),
    ("selexipague 600 mcg", "un"),
    ("selexipague 800 mcg", "un"),
    ("sevelamer 800 mg", "un"),
    ("sildenafila 20 mg", "un"),
    ("sildenafila 25 mg", "un"),
    ("sildenafila 50 mg", "un"),
    ("sirolimo 1 mg", "un"),
    ("sirolimo 2 mg", "un"),
    ("somatropina 1,33 mg injetável", "un"),
    ("somatropina 4 UI injetável", "un"),
    ("sulfassalazina 500 mg", "un"),
    ("tacrolimo 1 mg", "un"),
    ("tacrolimo 5 mg", "un"),
    ("tafamidis 20 mg", "un"),
    ("tafamidis 61 mg", "un"),
    ("teriflunomida 14 mg", "un"),
    ("timolol 5,0 mg/mL solução oftálmica", "un"),
    ("tiotrópio + olodaterol 2,5 mcg + 2,5 mcg", "un"),
    ("tobramicina 300 mg solução para inalação", "un"),
    ("tocilizumabe 20 mg/mL injetável", "un"),
    ("tofacitinibe 5 mg", "un"),
    ("topiramato 100 mg", "un"),
    ("topiramato 25 mg", "un"),
    ("topiramato 50 mg", "un"),
    ("toxina botulínica tipo a 100 UI injetável", "un"),
    ("toxina botulínica tipo a 500 UI injetável", "un"),
    ("travoprosta 0,04 mg/mL solução oftálmica", "un"),
    ("trientina 250 mg", "un"),
    ("triexifenidil 5 mg", "un"),
    ("triptorrelina 11,25 mg injetável", "un"),
    ("triptorrelina 22,5 mg injetável", "un"),
    ("triptorrelina 3,75 mg injetável", "un"),
    ("umeclidínio + vilanterol 62,5 mcg + 25 mcg", "un"),
    ("upadacitinibe 15 mg", "un"),
    ("ustequinumabe 45 mg injetável", "un"),
    ("vedolizumabe 300 mg/mL injetável", "un"),
    ("vigabatrina 500 mg", "un"),
    ("ziprasidona 40 mg", "un"),
    ("ziprasidona 80 mg", "un"),
    ("ácido ursodesoxicólico 150 mg", "un"),
    ("ácido ursodesoxicólico 300 mg", "un"),
    ("ácido ursodesoxicólico 50 mg", "un"),
    ("ácido zoledrônico 5 mg", "un"),
]
