#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Definitive Catalog
Pre-loaded items seed data for the items_catalog table
"""

DEFINITIVE_CATALOG: list[tuple[str, str]] = [
    ("Aciclovir 200mg", "un"),
    ("Aciclovir pomada", "un"),
    ("Acido folico 5mg", "un"),
    ("Alopurinol 100mg", "un"),
    ("Alopurinol 300mg", "un"),
    ("Amiodarona 200mg", "un"),
    ("Amitriptilina 25mg", "un"),
    ("Amitriptilina 75mg", "un"),
    ("Anfotericina B 50mg", "fr"),
    ("Atenolol 25mg", "un"),
    ("Atenolol 50mg", "un"),
    ("Azatioprina 50mg", "un"),
    ("Bromazepam 3mg", "un"),
    ("Bromoprida 10mg", "un"),
    ("Captopril 25mg", "un"),
    ("Carbamazepina 200mg", "un"),
    ("Carbamazepina 400mg", "un"),
    ("Cefalexina 500mg", "un"),
    ("Cefazolina 1g", "fr"),
    ("Ceftriaxona 1g", "fr"),
    ("Cetoconazol 200mg", "un"),
    ("Ciclofosfamida 50mg", "un"),
    ("Ciclosporina 100mg", "un"),
    ("Cimetidina 400mg", "un"),
    ("Ciprofloxacino 500mg", "un"),
    ("Citalopram 20mg", "un"),
    ("Clonazepam 2,5mg", "un"),
    ("Clorpromazina 25mg", "un"),
    ("Clorpromazina 100mg", "un"),
    ("Clordiazepoxido 10mg", "un"),
    ("Codeina 30mg", "un"),
    ("Dexametasona 4mg", "amp"),
    ("Diazepam 5mg", "un"),
    ("Diazepam 10mg", "amp"),
    ("Digoxina 0,25mg", "un"),
    ("Dipirona 500mg/ml", "amp"),
    ("Dipirona 500mg", "un"),
    ("Enalapril 10mg", "un"),
    ("Enalapril 20mg", "un"),
    ("Erythromycin 250mg", "un"),
    ("Espironolactona 25mg", "un"),
    ("Espironolactona 100mg", "un"),
    ("Fenitoína 100mg", "un"),
    ("Fenobarbital 100mg", "un"),
    ("Fluconazol 150mg", "un"),
    ("Fluoxetina 20mg", "un"),
    ("Furosemida 40mg", "un"),
    ("Furosemida 20mg", "amp"),
    ("Ganciclovir 500mg", "fr"),
    ("Glibenclamida 5mg", "un"),
    ("Gliclazida 80mg", "un"),
    ("Haloperidol 1mg", "un"),
    ("Haloperidol 5mg/ml", "amp"),
    ("Hidroclorotiazida 25mg", "un"),
    ("Hidrocortisona 100mg", "fr"),
    ("Imipramina 25mg", "un"),
    ("Insulina NPH", "fr"),
    ("Insulina Regular", "fr"),
    ("Interferon alfa 2B 10MIU", "fr"),
    ("Isossorbida 5mg", "un"),
    ("Isossorbida 20mg", "un"),
    ("Lactulona", "fr"),
    ("Levamisol 50mg", "un"),
    ("Levodopa + Benserazida 25/100mg", "un"),
    ("Levodopa + Carbidopa 25/250mg", "un"),
    ("Levotiroxina 25mcg", "un"),
    ("Levotiroxina 50mcg", "un"),
    ("Levotiroxina 100mcg", "un"),
    ("Lítio 300mg", "un"),
    ("Losartana 50mg", "un"),
    ("Manitol 20%", "fr"),
    ("Metformina 500mg", "un"),
    ("Metformina 850mg", "un"),
    ("Metildopa 250mg", "un"),
    ("Metildopa 500mg", "un"),
    ("Metoclopramida 10mg", "amp"),
    ("Metotrexato 2,5mg", "un"),
    ("Metronidazol 250mg", "un"),
    ("Metronidazol 500mg/100ml", "fr"),
    ("Midazolam 5mg/ml", "amp"),
    ("Morfina 10mg/ml", "amp"),
    ("Nifedipina 20mg", "un"),
    ("Nitrofurantoína 100mg", "un"),
    ("Omeprazol 20mg", "un"),
    ("Omeprazol 40mg", "fr"),
    ("Paracetamol 500mg", "un"),
    ("Paracetamol 500mg/ml", "amp"),
    ("Penicilina Benzatina 1.200.000UI", "fr"),
    ("Penicilina Benzatina 600.000UI", "fr"),
    ("Prednisona 5mg", "un"),
    ("Prednisona 20mg", "un"),
    ("Propranolol 10mg", "un"),
    ("Propranolol 40mg", "un"),
    ("Quetiapina 25mg", "un"),
    ("Quetiapina 100mg", "un"),
    ("Ranitidina 150mg", "un"),
    ("Risperidona 1mg", "un"),
    ("Risperidona 2mg", "un"),
    ("Sulfasalazina 500mg", "un"),
    ("Tamoxifeno 20mg", "un"),
    ("Teofilina 100mg", "un"),
    ("Teofilina 200mg", "un"),
    ("Tiocolquicosídeo 4mg", "un"),
    ("Tramadol 50mg", "un"),
    ("Tramadol 100mg/ml", "amp"),
    ("Trazodona 50mg", "un"),
    ("Valproato de Sódio 250mg", "un"),
    ("Valproato de Sódio 500mg", "un"),
    ("Varfarina 5mg", "un"),
    ("Verapamil 80mg", "un"),
    ("Vincristina 1mg", "fr"),
    ("Vitamina K", "amp"),
    ("Zidovudina 100mg", "un"),
    ("Zidovudina 10mg/ml", "fr"),
]
